### ISSUE TITLE
Add a link to rosettacode under Links

### ISSUE THREAD

**Issue by joebo** [jsoftware/j-playground#15]
Rosettacode is an incredible resource to learn more about J

**Comment by rdm** [comment]
I think the rosettacode link should maybe have `#mw-pages` added: https://rosettacode.org/wiki/Category:J#mw-pages

Many people are not going to think to scroll down.

**Comment by joebo** [comment]
> I think the rosettacode link should maybe have `#mw-pages` added: https://rosettacode.org/wiki/Category:J#mw-pages
> 
> Many people are not going to think to scroll down.

great idea. updated and closing this issue.
