### ISSUE TITLE
Add a [Hide] button to the multiline editor

### ISSUE THREAD

**Issue by rdm** [jsoftware/j-playground#17]
For casual users, there's little space left to view output when the multiline editor is up.

And, there's lots of white space taken up by the button row. Adding a [Hide] button (perhaps with float: right) would be a minor improvement here . 

Optionally, shrinking the multiline editor so that it occupies less vertical whitespace when it contains few lines, might be nice.

https://jsoftware.github.io/j-playground/bin/html/emj.html#code=%3E((2%23.3%20q%3A15%26%2B.)%7B(%7C.(%3B~%2C%26%3B)%3B%3A'Fizz%20Buzz')%3B~%22%3A)%26%3E1%2Bi.100

or

https://jsoftware.github.io/j-playground/bin/html/emj.html#code=%20%20%20extend%3D%3A%20%7B%7B%20y%3B(1%2Beach%20i._1%2B%7B.y)%2CL%3A0%20y%20%7D%7D%0D%0A%20%20%2010%2010%24(%23~%201%20p%3A%20%5D)10%23.%26%3E(%5B%3A~.%40%3Bextend%20each)%5E%3A%23%20%3E%3Ai.9

should demonstrate this issue, unless you have an extremely large browser window.

**Comment by joebo** [comment]
Thanks for the report. My experience seems different than yours. I am on a relatively high resolution - 1920x1080 and my browser looks like the screenshot below. Can you paste an screenshot of what you are seeing?

The multiline editor is intended to be about 50% of the vertical height but it sounds like that's not working correctly on your configuration?

Also, the View Menu has a "Toggle Multi-Line Editor" -- would the Hide button be in addition to that? Presumably to make it more obvious?

![image](https://user-images.githubusercontent.com/151573/161879892-5456beef-310a-4856-8ef0-9f631687c817.png)

![image](https://user-images.githubusercontent.com/151573/161879656-709d1c60-52f2-42c2-afe3-2f46f942b430.png)

**Comment by rdm** [comment]
Sure, I have basically the same sized screen, though I'm using a different browser:

![Screenshot (1)](https://user-images.githubusercontent.com/671269/161884988-4ee627d3-2d31-4c1f-88ab-871f481aab47.png)
 
If my browser is not full screen, it's even more cramped.

**Comment by joebo** [comment]
Ah, ok.. So we are seeing the same thing and just have different preferences (which is not expected at all)

I think it makes sense to shrink the multi line editor height to be like 1/3rd of the screen and leave 2/3rd for the output/repl as the default. I wasn't sure at first so I took a compromise at 50/50. I am leaning now also into having more space in the output area

It would also be have an option to increase the sizes of the various panels.  Super nice would be draggable heights and the dynamic height based on the content (with a minimum)

I will start with the 1/3rd and 2/3rd split first as that is easiest if that ratio sounds agreeable

**Comment by rdm** [comment]
I see four more lines in the output/repl part of the screen in your screenshot than in mine.

That said, it's true that I have not switched to a browser which would let me disable the tabs and location bar while in "full screen" mode.

**Comment by cdburke** [comment]
Just to note that the suggestion I made a few weeks ago re the old
playground has the features being requested for the new playground.

**Comment by joebo** [comment]
> Just to note that the suggestion I made a few weeks ago re the old playground has the features being requested for the new playground.

thanks chris -- if you post the code somewhere I'm happy to take a look at what it would take to integrate the wasm J engine into it or collaborate with you on it.

**Comment by cdburke** [comment]
Joe

I made a standalone package of this and put it on google drive. I already
shared it with Will, and will share it now with you and anyone else who is
interested. Instructions are below. I use linux but it should work on any
OS with minor changes to the startup scripts. It has the original
javascript source.

Feel free to use this anyway you like, either as a starting point, or just
for ideas.

I was happy with it before, except that it used http and needed https. Of
course this is no problem for the wasm engine.

The original is still up at https://code2.jsoftware.com/play.html .

Chris

----------------------------

Unzip the package into your home directory, which should now have a ~/play
directory.

Start two terminals in folder ~/play/bin. Then:

  ./runserver.command            - start a J server
  ./rungui.command               - start the gui, which connects to the
server

The J source is in ~/play/source. If you want to change this, define a
folder ~Play to point to ~/play/source. It will rebuild
~/play/bin/jplay.ijs.

The javascript source is in ~/play/jfe/lib.

**Comment by jonghough** [comment]
@cdburke 
Can you share the google drive with me?

**Comment by joebo** [comment]
> @cdburke Can you share the google drive with me?

I shared this with jon

@cdburke - your 2018 J Playground is really impressive work. I've written up #19  to cover the work I think that needs to be done as a next step here. I will take a stab at it ~~when I can unless jon gets a chance to~~ **DONE** (see #19).

**Comment by joebo** [comment]
Closing this issue as we are switching to the new UI (2018 playground) that doesn't have the toggle for multi-line
