### ISSUE TITLE
Surface plot does not render properly

### ISSUE THREAD

**Issue by joebo** [jsoftware/j-playground#18]
Rob H reported that the following surface plot example does not render properly in J Playground

```
'surface' plot +/~ *: sin i:10j50
```

https://jsoftware.github.io/j-playground/bin/html/emj.html#code='surface'%20plot%20%2B%2F~%20*%3A%20sin%20i%3A10j50

![image](https://user-images.githubusercontent.com/151573/161880265-4c03ca5d-39cb-4628-9e33-8bd1eb0b8d49.png)

**Comment by joebo** [comment]
Digging into this for several hours, I stumbled upon a perplexing workaround.

Adding a smoutput with a box before the line with box=. project box somehow causes the plot to display. If that smoutput is AFTER the following line it does not work. If the smoutput does NOT include a boxed output, it does not work. Truly puzzling

```
require 'graphics/plot'
coclass 'jzplot'

drawframebox3d=: 3 : 0
box=. (Box3d scalepos XYZDiff) movepos XYZMin
smoutput <'a' NB. <--- this line must be before the box=. project box
box=. project box
zbox=. {:"1 box
box=. }:"1 box
Box3dX=: /: _2 +/\ zbox
j=. <Box3dX /: 3#1 0 0 1
Box3dL=: j firstin &> 2 6 4 9 ;1 8 3 10 ;0 5 7 11
box=. fitgrafxy3d box
box=. 12 4$,box
box=. Box3dX{box
drawline iFRAME;AXISCOLOR;GUIDESIZE;box
drawline dolast iFRAME;AXISCOLOR;GUIDESIZE;3{.box
)

coclass 'base'
 'surface' plot +/~ *: sin i:10j50
 
 ```

[Playground Example](https://tinyurl.com/mr485hb9)

![image](https://user-images.githubusercontent.com/151573/161881026-6cd89a85-c0f3-420d-bc1a-7236c071051b.png)

**Comment by joebo** [comment]
It seems to be something with the project function.

```
project=: 3 : 0
dat=. }:"1 (y,.1) mp Tfm
dist=. ViewDist-{:"1 dat
((ViewDist*}:"1 dat)%dist),.dist
)
```

Bypassing it with a hardcoded value works without the smoutput

```
require 'graphics/plot'

boxData =: {{)n
_0.671152  _0.491315 3.35881
_0.720647 _0.0664976 3.12812
_0.671152  _0.491315 3.35881
_0.110045 _0.0981589 4.09701
_0.671152  _0.491315 3.35881
 0.157274   _0.86591 2.86667
_0.720647 _0.0664976 3.12812
_0.116611   0.269006 3.86632
_0.720647 _0.0664976 3.12812
 0.171038  _0.394563 2.63599
_0.110045 _0.0981589 4.09701
_0.116611   0.269006 3.86632
_0.110045 _0.0981589 4.09701
 0.625339  _0.342372 3.60487
 0.157274   _0.86591 2.86667
 0.171038  _0.394563 2.63599
 0.157274   _0.86591 2.86667
 0.625339  _0.342372 3.60487
_0.116611   0.269006 3.86632
 0.668093  0.0616482 3.37419
 0.171038  _0.394563 2.63599
 0.668093  0.0616482 3.37419
 0.625339  _0.342372 3.60487
 0.668093  0.0616482 3.37419
}}
box =: > ". each LF cut boxData


coclass 'jzplot'

drawframebox3d=: 3 : 0
box=. (Box3d scalepos XYZDiff) movepos XYZMin
box =. box_base_
smoutput box
zbox=. {:"1 box
box=. }:"1 box
Box3dX=: /: _2 +/\ zbox
j=. <Box3dX /: 3#1 0 0 1
Box3dL=: j firstin &> 2 6 4 9 ;1 8 3 10 ;0 5 7 11
box=. fitgrafxy3d box
box=. 12 4$,box
box=. Box3dX{box
drawline iFRAME;AXISCOLOR;GUIDESIZE;box
drawline dolast iFRAME;AXISCOLOR;GUIDESIZE;3{.box
)

coclass 'base'
 'surface' plot +/~ *: sin i:10j50
 
```
[Example](https://tinyurl.com/ms5773j7)

**Comment by rdm** [comment]
Oddly, if I capture the result of `project`, it looks nothing like the value you have here for `box`. Possibly, because `project` is used 8 times here.

I get a result with shape `2601 3` for the final value from `project`, so I will not post it here. Instead, here's what I used:

```
project_jzplot_=: 3 : 0
dat=. }:"1 (y,.1) mp Tfm
dist=. ViewDist-{:"1 dat
echo <dist
R_base_=:((ViewDist*}:"1 dat)%dist),.dist
)
'surface' plot +/~ *: sin i:10j50
```

**Comment by joebo** [comment]
I'm guessing it's memory related. This works

```
require 'graphics/plot'
coclass 'jzplot'

project=: 3 : 0
NB. why does this work?
1 $ 0
dat=. }:"1 (y,.1) mp Tfm
dist=. ViewDist-{:"1 dat
((ViewDist*}:"1 dat)%dist),.dist
)

coclass 'base'
 'surface' plot +/~ *: sin i:10j50
 ```

https://jsoftware.github.io/j-playground/bin/html/emj.html#code=require%20'graphics%2Fplot'%0D%0Acoclass%20'jzplot'%0D%0A%0D%0Aproject%3D%3A%203%20%3A%200%0D%0ANB.%20why%20does%20this%20work%3F%0D%0A1%20%24%200%0D%0Adat%3D.%20%7D%3A%221%20(y%2C.1)%20mp%20Tfm%0D%0Adist%3D.%20ViewDist-%7B%3A%221%20dat%0D%0A((ViewDist*%7D%3A%221%20dat)%25dist)%2C.dist%0D%0A)%0D%0A%0D%0Acoclass%20'base'%0D%0A%20'surface'%20plot%20%2B%2F~%20*%3A%20sin%20i%3A10j50%0D%0A%20

**Comment by joebo** [comment]
fixed by adding gemm into the build and reverting hacks to cip.c
