### ISSUE TITLE
Basic viewmat support in ported jplayground

### ISSUE THREAD

**Issue by joebo** [jsoftware/j-playground#22]
It would be nice to have viewmat working in the ported jplayground. This implementation is hacky as it just overwrites 

```
viewmat_jviewmat_=: 3 : 0
'' viewmat y
:
a=. '' conew 'jviewmat'
xx__a=: x [ yy__a=: y
if. VIEWMATGUI do.
  empty vmrun__a ''
else.
  empty vmrun__a ''
  (setalpha no_gui_bitmap__a'') writepng jpath '~temp/',TITLE__a,'.png'
  TITLE=. TITLE__a
  destroy__a ''

  d=. tobase64_base_ fread (<'/viewmat.png')
  imghtml_j_ =: '8',d
  (2!:0) plotJS_j_
end.
)
```

![image](https://user-images.githubusercontent.com/151573/162553953-5d677e1e-8b71-4fa8-914f-9b2baa79d652.png)

**Comment by cdburke** [comment]
See also Examples|Viewmat, then Edit Run|All Lines .
