### ISSUE TITLE
Loading stdlib on startup

### ISSUE THREAD

**Issue by jonghough** [jsoftware/j-playground#4]
Do we want the standard library to be loaded? Although the primitives work, no stdlib verbs are available.

I am actually not sure how to execute a whole script as `jdo` only executes a single line.

**Comment by joebo** [comment]
> Do we want the standard library to be loaded? Although the primitives work, no stdlib verbs are available.

Great idea. I started some work on this and ran out of time to keep rolling on it. The good news is that it's easy to package the scripts with the binary with --preload-file

![image](https://user-images.githubusercontent.com/151573/156188386-699fc340-3daf-4f8d-a2f3-48922c7020bd.png)

I updated our version of xf.c to allow listing directories and reading files

![image](https://user-images.githubusercontent.com/151573/156188240-b30e2702-b450-41f0-be38-5648cdebe5d6.png)

Reading files is still broken for me... I think there's something deep in the jsrc that I need to debug.

> 
> I am actually not sure how to execute a whole script as `jdo` only executes a single line.

In the latest version use the menu View -> Toggle Multi-Line Editor and then paste the multi-line script in and click Run

**Comment by jonghough** [comment]
Wrapping `stdlib.ijs` in a js file, and loading it using  
```  
jsetstr('CODE', JSTDLIB);
 out = jdo1("(0!:101) CODE");
 ```
 results in an error. 
```
|domain error
|   notdef=.0:~:4    !:0@<
|[-74] 
```
It seems several foreigns are not available in j-playground, which should probably be expected, as several file based operations are not going to be available in the browser. But we then need a modified stdlib. Or, as you said, bake stdlib in to the wasm build.

**Comment by jonghough** [comment]
Even conversions are not available.
```
        (3!:1) 4
|domain error
|   (3    !:1)4
 ```

**Comment by joebo** [comment]
> Even conversions are not available.
> 
> ```
>         (3!:1) 4
> |domain error
> |   (3    !:1)4
> ```

Many foreigns are still commented out as a shortcut to get it to build. We will need to work through the build errors

https://github.com/jsoftware/j-playground/blob/eb4fc374d883fec0aa76b2dc2e129b478e9b8a00/jsrc/x.c#L71

**Comment by joebo** [comment]
This should be working now. I bundled jlibrary with the wasm. It adds about 1MB to the .wasm file. It is executed on startup https://github.com/jsoftware/j-playground/commit/1ff6129abe40fc7a500804dde1b3d9c235755865#diff-3333a80fc003880a91bf99391f6bf7cc4a08bc0c8b3378e1db84850bcd0be46dR72

Great suggestion!

**Comment by joebo** [comment]
Apologies for all the commits on this. I was testing on my Samsung Galaxy S20FE and now it crashes on loading. I also have 77 tabs open so maybe it's out of memory on mobile. I tried turning off automatic loading of stdlib and it didn't make any difference in the mobile behavior -- it still crashed for me. I'm re-enabling the automatic loading of stdlib.


Firefox mobile works on my Android Samsung Galaxy S20FE, but chrome does not.  I don't want to close all my chrome mobile tabs so any additional testing on Chrome would be helpful.

**Comment by bilam** [comment]
is there any way that J can know the current platform is wasm so that stdlib can be patched to work with it?

**Comment by joebo** [comment]
> is there any way that J can know the current platform is wasm so that stdlib can be patched to work with it?

This is still an experiment in my mind, so I'm not yet thinking about the correct way to integrate back into the main branch. I didn't want to slow down the experiment by getting too caught up in that yet.

I hacked in a compile time constant at [(9!:12)](https://github.com/jsoftware/j-playground/blob/j903_wasm/jsrc/xa.c#L209), which can be used at https://github.com/jsoftware/j-playground/blob/j903_wasm/jlibrary/system/main/stdlib.ijs#L14 down the road with a IFWASM, just like we have IFUNIX
