### ISSUE TITLE
New BQN interface syntax highlights and partial evaluations

### ISSUE THREAD

**Issue by bobtherriault** [jsoftware/j-playground#5]
Not really an issue, more of a target that we could look at to see if this sort of functionality is useful. 
https://bqnpad.mechanize.systems/

**Comment by joebo** [comment]
@bobtherriault  do you still want to keep this issue open and tracked? I don't know how relevant it is any more with the new Playground. Please close if you feel we're in a good spot or comment otherwise. I'm grooming the issues log

**Comment by bobtherriault** [comment]
Although partial evaluation is interesting, I think that the Playground should only do this if it put in place in Jqt, so I am closing the issue.

**Comment by bobtherriault** [comment]
Although partial evaluation is interesting, I think that the Playground should only do this if it put in place in Jqt, so I am closing the issue.

**Comment by joebo** [comment]
Thanks bob for reporting and closing it. I agree it is a worthwhile idea to
keep in the idea log as a closed topic for now. Thanks again!
