### ISSUE TITLE
Add "Toggle Edit Window" as option under View menu

### ISSUE THREAD

**Issue by joebo** [jsoftware/j-playground#51]
As a user, I'd like to be able to hide the Edit window if I only want to work on the terminal (e.g. running a lab)

View
- Hide/Show Edit Window

Not sure the best menu item label yet -- open to feedback

**Comment by cdburke** [comment]
That label sounds good.

BTW, you can hide the edit window by moving the slider to the edge. This allows the user to restore it by grabbing the slider and moving it in.

I don't remember a function to do this, but you could hack it by using the "slidehb" or "slidevb' functions depending on the current layout. 

For example, in the javascript console, try:

  layout.exec("slidevb(2000)")

Would you like me to write a show/view edit window function for this?

**Comment by joebo** [comment]
Thanks chris -- yes, that would be much appreciated if you wrote the function for it.

**Comment by cdburke** [comment]
Done. 

Select the menu Hide/Show Edit (Shift+Ctrl+E) to toggle the edit window on off.

Run function showedit(true/false) to hide/show the edit window.
