### ISSUE TITLE
duplicate output in term under some conditions

### ISSUE THREAD

**Issue by joebo** [jsoftware/j-playground#53]
There are certain conditions that cause output to be duplicated in the term.

It can be seen on the first example 

![image](https://user-images.githubusercontent.com/151573/168591441-d4963551-5490-4cd0-b165-13e04a96d172.png)

It shows up on a simple plot example too [Playground link](https://jsoftware.github.io/j-playground/bin/html2/#code=plot%20p%3Ai.5)

![image](https://user-images.githubusercontent.com/151573/168591776-b92fe840-0733-4d4a-adb0-df09a5dc8716.png)

More triage is needed here. Is it only on plot or do other scenarios cause duplicated outputs?

__edit__:  the bug report was very helpful and identified one of the causes as blank lines. this is fixed. The issue still remains with echoing the cmd that generated no output (e.g. assignment) or plot

**Comment by plj541** [comment]
At least two other causes, assignment and blank lines in Edit are followed by duplicates.

[Bug Report.pdf](https://github.com/jsoftware/j-playground/files/8706657/Bug.Report.pdf)

**Comment by plj541** [comment]
Forgot to say, red for inappropriate duplicates, and yellow for missing output. Actual output on local copy of J, then manipulated to look like what I see on web page.

**Comment by joebo** [comment]
The bug report was very helpful and identified the cause as blank lines. this is fixed

**Comment by joebo** [comment]
Reopening this issue. As mentioned in plj541's comments above, it's more than just blank lines. Assignment and plot also echo the command when it probably shouldn't to be consistent with jconsole and jqt.

**Comment by joebo** [comment]
As a clue, it appears that we are outputting correctly on the prototype playground https://jsoftware.github.io/j-playground/bin/html/emj.html. 
On the prototype
- [x] assignment doesn't echo the command
- [x] plot doesn't echo the command
- [x] blank lines do not echo the previous command

On the new playround
- [ ] assignment doesn't echo the command
- [ ] plot doesn't echo the command
- [x] blank lines do not echo the previous command

The prototype playground overwrote the out function, which is used by emscripten to output stdout, to output to the terminal, whereas the new playground uses tcmreturn.  Both use (0!:101) to execute the lines

https://github.com/jsoftware/j-playground/blob/j903_wasm/bin/html2/localj.js#L18
https://github.com/jsoftware/j-playground/blob/j903_wasm/bin/html/app.js#L177

It's not yet obvious how to make the new playground behave like the prototype and will take some tinkering.

**Comment by cdburke** [comment]
I will get this. I'm pretty sure the original 2018 behaved correctly.

**Comment by plj541** [comment]
Today's release is much improved.  Assignment and empty lines no longer produce unwanted output.

I was able to remove the rest of the issues I've reported by:
    '' NB. No longer a leading comment
    ''[ load '...
    ''[ plot
    ''[ pd

**Comment by plj541** [comment]
Today's release is much improved. Assignment and empty lines no longer
produce unwanted output.

I was able to remove the rest of the issues I've reported by:
'' NB. No longer a leading comment
''[ load '...
''[ plot
''[ pd

I've also left this message as a comment to issue #53.

**Comment by plj541** [comment]
I left out assignment, which still needs work:
  ''[ now=: 'foo...

**Comment by joebo** [comment]
> I will get this. I'm pretty sure the original 2018 behaved correctly.

thanks for the help chris. I was going to try the original 2018 version and it was offline so I couldn't verify. I appreciate the help with this one. I have some ideas too if it starts to become a time sink for you

**Comment by cdburke** [comment]
This should be fixed now.

**Comment by plj541** [comment]
I agree that the subject line of Issue #53 has been fixed.

I've opened

Initial parts of Comment do no appear in output, also output cannot be
copied #63

to address the remaining issues.

**Comment by joebo** [comment]
Reopening with this example

```
NB. CORRECT: single line does not echo
t=: ?~10

NB. BUG: multi-line echos
foo=: 3 : 0
a=. 2 + y
5 * a
)

```
[J Playground](https://jsoftware.github.io/j-playground/bin/html2/#code=NB.%20CORRECT%3A%20single%20line%20does%20not%20echo%0At%3D%3A%20%3F~10%0A%0ANB.%20BUG%3A%20multi-line%20echos%0Afoo%3D%3A%203%20%3A%200%0Aa%3D.%202%20%2B%20y%0A5%20*%20a%0A%29%0A)

![image](https://user-images.githubusercontent.com/151573/170532558-8c4db2d6-fcfa-42d2-841c-d277c783fdc6.png)

**Comment by joebo** [comment]
Multi-line assignments are correctly not echoing now. No other regressions were noted

![image](https://user-images.githubusercontent.com/151573/170534876-0a514a72-5358-418f-8f98-d172856c97c5.png)
