### ISSUE TITLE
{{ }} only works when {{ is NOT immediately followed by )

### ISSUE THREAD

**Issue by plj541** [jsoftware/j-playground#54]
9!:14 ''
j903/j32/linux/beta/GPL3/unknown/2022-05-15T20:44:01/clang-14-0-0/SLEEF=0

fun=: {{
 y- x
}}

fun=: {{)n
|control error
|[-1] 
y- x
|value error
|   y-    x
|[-0] 
}}
|control error
|[-0] 

fun=: {{)d
|control error
|[-1] 
y- x
|value error
|   y-    x
|[-0] 
}}
|control error
|[-0]

**Comment by joebo** [comment]
Thanks for the report. This is working but I'd like another pair of eyes on it before I close it out.  It seems there would be an edge case when the {{ is enclosed in quotes.

Here is a working version [Playground](https://jsoftware.github.io/j-playground/bin/html2/#code=%7B%7B%29n%0A1%202%203%0A%7D%7D)

I tried breaking my implementation with things like

```
badParse =: '{{' ,
'blah'
```

but it seemed to work as expected

I'll keep this open for a day or so in case someone wants to try and break the simple implementation I put in

**Comment by plj541** [comment]
Your fix removed all the examples I gave. But as usual, I try to report the
simplest example that results in the error. When I tried to put it in my
traditional noun I got a new error.

help=: 0 : 0
 i.3 4
{: {{)n
1 2 3
}}
)

Works, but
help=:0 : 0
help=: 0 :0
help=: 0 def 0

All now fail on the first line.

**Comment by cdburke** [comment]
should be fixed in the latest repo

**Comment by plj541** [comment]
It took me a bit to determine what you just fixed. I believe it was the
nested comment below. However, the {{)n form, and all of its cousins a, c,
d and m now fail again. I believe this increases the need for regression
testing.

I'd start with my favorite debugging adverb to create a regression test.
I'm happy to chat about this if you are interested.

Del=: {{)a
  NB. Copy lines from the screen, then  m Del  to capture the definition
  m : (wdclippaste_z_ '')
}}
NB. Secondary report in Issue #54
help=: 0 : 0
 i.3 4
{: {{)n
1 2 3
}}
)

NB. Initial report in Issue #54
fun=: {{
y- x
}}

fun=: {{)n
 this
}}
