### ISSUE TITLE
Duplicate results from single line sentence.

### ISSUE THREAD

**Issue by bobtherriault** [jsoftware/j-playground#6]
Entering a single line J sentence such as `i. 3 4` in the main text area results in two versions of the result. The first is double spaced and the second is single spaced immediately below the first. Entering the same command in the multiline area causes one result appropriately singled spaced.  Seems to be some kind of echoing happening with commands executed in the main text area. May be related to the multi-line editor echoing its results.

**Comment by bobtherriault** [comment]
Thanks Joe, 

A small adjustment still required for the multiline output which indents the command line an extra 3 spaces compared to the main text area.

**Comment by joebo** [comment]
> A small adjustment still required for the multiline output which indents the command line an extra 3 spaces compared to the main text area.

Thanks bob! I meant to add a reply yesterday after I committed the change. I was going to note that the double echo was fixed but there were still some leading space issues.

I just committed a change that looks fine on my side. Can you take a look too and close the issue if you think it's resolved?

**Comment by bobtherriault** [comment]
Yep, that fixed it Joe,

Just to be really clear, when I put in an issue there is no expectation for priority action! You are putting in far more work on this than is expected and I don't want to abuse the gift that you are giving us.

Cheers, bob

**Comment by joebo** [comment]
> Yep, that fixed it Joe, Just to be really clear, when I put in an issue there is no expectation for priority action! You are putting in far more work on this than is expected and I don't want to abuse the gift that you are giving us. Cheers, bob
 
Glad to hear! No worries. I was itching to wrap it up once I got started on it yesterday :)... I got started on it yesterday because I thought it was fun so no feeling of pressure at all! I appreciate your comments
