### ISSUE TITLE
Issues on older iPhones

### ISSUE THREAD

**Issue by razetime** [jsoftware/j-playground#62]
[reported on the forums](http://www.jsoftware.com/pipermail/general/2022-May/039197.html)

(1) Run All Lines only executes the line the cursor is on (and I do
not seem to have a mechanism to "select all" in the editor pane), and

(2) The menu bar has a tendency to vanish.

on an iphone.

**Comment by rdm** [comment]
run all lines now works on my iphone.

And, so far at least, the menu bar has not vanished on me.
