### ISSUE TITLE
Error Building with emcc

### ISSUE THREAD

**Issue by jonghough** [jsoftware/j-playground#73]
I have not tried building for a while. There seems to be a new set of errors, related to BLAS and LAPACK, when running

`make -f makefile.wasmer clean j` :

```
error: undefined symbol: dgemm_nn (referenced by top-level compiled C/C++ code)
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _dgemm_nn may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: igemm_nn (referenced by top-level compiled C/C++ code)
warning: _igemm_nn may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: zgemm_nn (referenced by top-level compiled C/C++ code)
warning: _zgemm_nn may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
emcc: error: '/emsdk/node/14.18.2_64bit/bin/node /emsdk/upstream/emscripten/src/compiler.js /tmp/tmpo9ann92c.json' failed (returned 1)
make: *** [makefile.wasmer:25: j] Error 1
```

**Comment by jonghough** [comment]
Adding `-s ERROR_ON_UNDEFINED_SYMBOLS=0` to the makefile.wasmer `j` command, reoslves it somewhat. 
There are still warnings, but `emj.wasm` is built.

**Comment by joebo** [comment]
Thanks for reporting. The wasmer  build has become less useful as time has
gone on and isn't maintained as well I should. I would suggest sticking to
makefile.html for now

I will look into fixing the wasmer compile

**Comment by jonghough** [comment]
Oh I see, will try building with makefile.html.
I think, in that case we should update the README a little.

**Comment by joebo** [comment]
Closing out with the latest commit 08d8f4f4d7bf73fcc94a3dcc6cdbc8617117549f ... Can you update the README with any changes you have in mind?
