### ISSUE TITLE
Remove html folder and move html2 to html

### ISSUE THREAD

**Issue by jonghough** [jsoftware/j-playground#74]
Is the `bin/html` folder needed now? It seems we only need `bin/html2`, which contains the modified code, originally form Chris Burke. It seems this has been chosen to be used as the frontend.

For the sake of simplicity, I suggest deleting html/, and moving html2/ -> html/.

Or am I wrong, and we still need html/?

**Comment by joebo** [comment]
The original prototype code (/bin/html) was reported to be easier to work
with than (/bin/html2) on iPhones and I use it occasionally on my phone
too.

I would suggest keeping both for now. Long term we will want to figure out
a better mobile interface and permanent links. We can use this issue to
track that effort if we want.

Raul mentioned (and I have seen some) there are some external links that
point to /bin/html...We will want to keep some shell page there at a
minimum that redirects to the permanent link once we have it

**Comment by rdm** [comment]
I should add: at one point the html2 version had some bugs which specifically hit the iphone. Those seem to have been fixed. 

However, there's still a somewhat cosmetic issue, which is that the iphone is usually used in "portrait mode" while the side-by-side html2 UI is designed for "landscape mode".

**Comment by cdburke** [comment]
The UI can be flipped to portrait mode. Perhaps this setting should be saved?

Also, could the better mode be picked at start up?

**Comment by rdm** [comment]
I think `screen.availHeight > screen.availWidth` distinguishes between portrait and landscape mode.

That said, using the ScreenOrientation.onchange event handler to flip the UI might also be nice.

**Comment by cdburke** [comment]
It would be good to merge html and html2 into a single UI.

I quite like the blank page you get with html, and am wondering if the Edit page in html2 should only appear on request, or when one of the Examples is opened. That should at least make it easier for mobile users.

Also, do we need the Term/Edit panel headers or are the colors enough to distinguish the two panels?

**Comment by JoeBognerINSIGHT** [comment]
> It would be good to merge html and html2 into a single UI.

I also agree it would be nice to eventually merge the two as long as it doesn't make the code overly complicated. 



> I quite like the blank page you get with html,

Sorry for the new confusion, are you referring to /html/emj.html or the new /html/index.html I added yesterday as part of #76 (shown below is /html/index.html)

![Screenshot_20220527-121758_Chrome](https://user-images.githubusercontent.com/21956552/170739695-c15266a1-b2cc-455a-8aad-77ee6590c76c.jpg)

**Comment by joebo** [comment]
> It would be good to merge html and html2 into a single UI.

I also agree it would be nice to eventually merge the two as long as it doesn't make the code overly complicated. 



> I quite like the blank page you get with html,

Sorry for the new confusion, are you referring to /html/emj.html or the new /html/index.html I added yesterday as part of #76 (shown below is /html/index.html)

![image](https://user-images.githubusercontent.com/151573/170773528-5770331d-0327-448b-bc32-5bf275756a19.png)

**Comment by cdburke** [comment]
I meant the new index.html page.

**Comment by joebo** [comment]
> I meant the new index.html page.

Glad to hear. I have been using it for a few hours on my phone and I have quite liked it. If @rdm can try it on his iPhone and if it works satisfactorily I will drop the old emj.html and have it redirect to index.html

**Comment by rdm** [comment]
https://jsoftware.github.io/j-playground/bin/html/ mostly functions on my iphone, but the "menu bar" floats over the multiline editor (which was open by default). Toggling the editor out of sight left the bar floating over the session pane, about one "bar height" below where it should have been (and with the corresponding session pane going to the top of the screen rather than stopping at the base of the bar -- it could have been worse though: it could have stopped just below where the menu bar should have appeared, which would have made it more difficult to use, as that would have hidden the top of the pane).

Also, there were some scrolling oddities (initially, the top pane was "too high" but that settled down after I messed with it for a few seconds).

**Comment by joebo** [comment]
> https://jsoftware.github.io/j-playground/bin/html/ mostly functions on my iphone, but the "menu bar" floats over the multiline editor (which was open by default). Toggling the editor out of sight left the bar floating over the session pane, about one "bar height" below where it should have been (and with the corresponding session pane going to the top of the screen rather than stopping at the base of the bar -- it could have been worse though: it could have stopped just below where the menu bar should have appeared, which would have made it more difficult to use, as that would have hidden the top of the pane).


Thanks for the report. If it's not too much trouble, can you upload a screenshot of what you see? Here is what I see:
![image](https://user-images.githubusercontent.com/151573/170773353-5181fa9d-02b3-4689-a530-2c13386a7c40.png)

Also, I am leaning into keeping the multi-line editor visible by default, but that is based on how I use it. If others feel differently I can be swayed. I could add some text to the placeholder (which is the default grey text) to let the user know they can hide it from the View menu.

**Comment by rdm** [comment]
I should have taken a screenshot.

That said, I have not been able to reproduce this problem.

**Comment by joebo** [comment]
Closing this as completed with #76.  One optimization would be to have these versions share the same emj.js and emj.wasm by using 

```
            var Module = {}
            Module['locateFile'] = function(file) { 
                //pull dependencies from /bin/html
                return 'https://cdn.jsdelivr.net/gh/jsoftware/j-playground@bf3f4535276c9721e0e79141c3c1376b1aa39d4d/bin/html/' + file;
            }
``` 
or equivalent, but that can be another issue for another time. We can open a new issue to track thinking on a consolidated UI when the time comes
