### ISSUE TITLE
Output trims initial blanks, so first line of multiline output can appear ragged

### ISSUE THREAD

**Issue by plj541** [jsoftware/j-playground#78]
10*i. 3 4
0 10  20  30
40 50  60  70
80 90 100 110

**Comment by joebo** [comment]
Thanks. I was afraid my "fix" would have this issue.

Without the trim I was getting blank lines on the multi-line assigments
```
ret = ret.replace(cmd, "").trim();
```
https://github.com/jsoftware/j-playground/blob/j903_wasm/bin/html2/localj.js#L19

I think a better way to handle this may be putting the trim on the length check

```
if (ret.trim().length>0) {
```
https://github.com/jsoftware/j-playground/blob/j903_wasm/bin/html2/localj.js#L29

Untested. If someone else doesn't pick this up I will attempt it later today. It would be nice to somehow have some unit tests or programmatic validation around this logic as it's pretty fragile. I will think more about that too

**Comment by cdburke** [comment]
I will look at this, and  #77 which is also a multiline problem.

**Comment by cdburke** [comment]
Fixed now.
