### ISSUE TITLE
Large files cannot be downloaded using httpget

### ISSUE THREAD

**Issue by joebo** [jsoftware/j-playground#80]
When downloading a 5mb file, WASM throws a ```RuntimeError: memory access out of bounds``` error when calling jsetstr

Example
```
httpget 'https://raw.githubusercontent.com/nytimes/covid-19-data/master/rolling-averages/us-counties-recent.csv'
```
[J Playground](https://jsoftware.github.io/j-playground/bin/html2/#code=httpget%20'https%3A%2F%2Fraw.githubusercontent.com%2Fnytimes%2Fcovid-19-data%2Fmaster%2Frolling-averages%2Fus-counties-recent.csv')

This is the faulty javascript code
```
   httpgetJS_jpacman_
let url = jgetstr("URL_httpget_");
    var request = new XMLHttpRequest();
    request.open('GET', url, false);
    request.send(null);
    console.log(url);
    if (request.status === 200) {
      //console.log(request.responseText);
      jsetstr("RESPONSE_httpget_",request.responseText); 
    }   
```

```
RuntimeError: memory access out of bounds
    at em_jsetstr (emj.wasm:0xb2459)
    at ccall (emj.js:835:18)
    at emj.js:858:12
    at eval (eval at execHost (emj.js:1672:77), <anonymous>:8:7)
    at execHost (emj.js:1672:77)
    at jthost (emj.wasm:0xc3c50)
    at byn$fpcast-emu$jthost (emj.wasm:0x221e5a)
    at secf1 (emj.wasm:0x1b26aa)
    at byn$fpcast-emu$secf1 (emj.wasm:0x226223)
    at jtparsea (emj.wasm:0x152645)
```

**Comment by joebo** [comment]
Fixed based on this solution: https://github.com/emscripten-core/emscripten/issues/6860

**Comment by rdm** [comment]
It's probably worth checking whether Module.stringToUTF8() corrupts (or allows) arbitrary byte sequences.

Other possibilities here might be the deprecated writeStringToMemory method. Or, if the deprecation makes that too risky: writeAsciiToMemory with ASSERTIONS disabled, or maybe even writeArrayToMemory (though that one is not documented well enough for me to tell whether it would work here).
