### ISSUE TITLE
Bill Szuch simple tutorials

### ISSUE THREAD

**Issue by cdburke** [jsoftware/j-playground#82]
Bill asked to run simple tutorials in the playground. 

I made a quick hack for this. There are some scripts in repo https://github.com/cdburke/simple. To load the raw content, try for example:

openscript 'https://raw.githubusercontent.com/cdburke/simple/master/structural.ijs'

This writes to the Edit window and puts the cursor at the top. Then Ctrl+Enter will step through the script.

**Comment by cdburke** [comment]
Do the scripts have to be in github to satisfy CORS rules?

**Comment by joebo** [comment]
> Do the scripts have to be in github to satisfy CORS rules?

No, but GitHub is the easiest way to share that I found so far that supports CORS. The web server just has to send the right http headers: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by cdburke** [comment]
Got it. I wondered why I could not read from the jsoftware server, but this now works:

https://jsoftware.github.io/j-playground/bin/html2/#url=https://www.jsoftware.com/download/simple/structural.ijs

Your "url=" method is really nice.
