### ISSUE TITLE
Examples UI does not work

### ISSUE THREAD

**Issue by plj541** [jsoftware/j-playground#96]
When first released this popped up a browser window and you could change the color of the circle. Now running the code just leaves a line on the screen, but the session doesn't appear to be damaged.

**Comment by joebo** [comment]
Thanks for the report. This is fixed. You may need to clear cache or ctrl+refresh to get the latest version

**Comment by plj541** [comment]
All I had to do was click on my link. It works exactly as it should.

**Comment by joebo** [comment]
Good to know. Thanks for confirming it works!
